In [38]:
import pandas as pd

df = pd.read_csv("iris.csv")

df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [39]:
import numpy as np
np.unique(df['variety'])

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [40]:
df['class'] = df['variety'].replace({"Setosa":0, "Versicolor":1, "Virginica":2})

/tmp/ipykernel_4256/55725183.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['variety'].replace({"Setosa":0, "Versicolor":1, "Virginica":2})


In [41]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'class'],
      dtype='object')

In [42]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety  class
0           5.1          3.5           1.4          0.2  Setosa      0
1           4.9          3.0           1.4          0.2  Setosa      0
2           4.7          3.2           1.3          0.2  Setosa      0
3           4.6          3.1           1.5          0.2  Setosa      0
4           5.0          3.6           1.4          0.2  Setosa      0

In [43]:
df = df.dropna()

In [44]:
df = df.fillna(0)

In [45]:
df = df.drop_duplicates()

In [46]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width       class
count    149.000000   149.000000    149.000000   149.000000  149.000000
mean       5.843624     3.059732      3.748993     1.194631    0.993289
std        0.830851     0.436342      1.767791     0.762622    0.817847
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.300000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  149 non-null    float64
 1   sepal.width   149 non-null    float64
 2   petal.length  149 non-null    float64
 3   petal.width   149 non-null    float64
 4   variety       149 non-null    object 
 5   class         149 non-null    int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 8.1+ KB


In [48]:
list = df.stack().to_list()
print(list)

[5.1, 3.5, 1.4, 0.2, 'Setosa', 0, 4.9, 3.0, 1.4, 0.2, 'Setosa', 0, 4.7, 3.2, 1.3, 0.2, 'Setosa', 0, 4.6, 3.1, 1.5, 0.2, 'Setosa', 0, 5.0, 3.6, 1.4, 0.2, 'Setosa', 0, 5.4, 3.9, 1.7, 0.4, 'Setosa', 0, 4.6, 3.4, 1.4, 0.3, 'Setosa', 0, 5.0, 3.4, 1.5, 0.2, 'Setosa', 0, 4.4, 2.9, 1.4, 0.2, 'Setosa', 0, 4.9, 3.1, 1.5, 0.1, 'Setosa', 0, 5.4, 3.7, 1.5, 0.2, 'Setosa', 0, 4.8, 3.4, 1.6, 0.2, 'Setosa', 0, 4.8, 3.0, 1.4, 0.1, 'Setosa', 0, 4.3, 3.0, 1.1, 0.1, 'Setosa', 0, 5.8, 4.0, 1.2, 0.2, 'Setosa', 0, 5.7, 4.4, 1.5, 0.4, 'Setosa', 0, 5.4, 3.9, 1.3, 0.4, 'Setosa', 0, 5.1, 3.5, 1.4, 0.3, 'Setosa', 0, 5.7, 3.8, 1.7, 0.3, 'Setosa', 0, 5.1, 3.8, 1.5, 0.3, 'Setosa', 0, 5.4, 3.4, 1.7, 0.2, 'Setosa', 0, 5.1, 3.7, 1.5, 0.4, 'Setosa', 0, 4.6, 3.6, 1.0, 0.2, 'Setosa', 0, 5.1, 3.3, 1.7, 0.5, 'Setosa', 0, 4.8, 3.4, 1.9, 0.2, 'Setosa', 0, 5.0, 3.0, 1.6, 0.2, 'Setosa', 0, 5.0, 3.4, 1.6, 0.4, 'Setosa', 0, 5.2, 3.5, 1.5, 0.2, 'Setosa', 0, 5.2, 3.4, 1.4, 0.2, 'Setosa', 0, 4.7, 3.2, 1.6, 0.2, 'Setosa', 0, 4.8, 3.1,

In [49]:
sepal_length = df['sepal.length'].tolist()
sepal_width = df['sepal.width'].tolist()
petal_length = df['petal.length'].tolist()
petal_width = df['petal.width'].tolist()
variety = df['variety'].tolist()

# Afisarea primelor 5 rânduri ale DataFrame-ului pentru confirmare
print(df.head())

# Afisarea listelor
print("Sepal Length:", sepal_length)
print("Sepal Width:", sepal_width)
print("Petal Length:", petal_length)
print("Petal Width:", petal_width)
print("Variety:", variety)

   sepal.length  sepal.width  petal.length  petal.width variety  class
0           5.1          3.5           1.4          0.2  Setosa      0
1           4.9          3.0           1.4          0.2  Setosa      0
2           4.7          3.2           1.3          0.2  Setosa      0
3           4.6          3.1           1.5          0.2  Setosa      0
4           5.0          3.6           1.4          0.2  Setosa      0
Sepal Length: [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0, 5.0, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4, 5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6, 5.3, 5.0, 7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6.0, 5.7, 5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5.0, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4,

In [50]:
df['x'] = df[df.columns[:4]].values.tolist()
df['x']

0      [5.1, 3.5, 1.4, 0.2]
1      [4.9, 3.0, 1.4, 0.2]
2      [4.7, 3.2, 1.3, 0.2]
3      [4.6, 3.1, 1.5, 0.2]
4      [5.0, 3.6, 1.4, 0.2]
               ...         
145    [6.7, 3.0, 5.2, 2.3]
146    [6.3, 2.5, 5.0, 1.9]
147    [6.5, 3.0, 5.2, 2.0]
148    [6.2, 3.4, 5.4, 2.3]
149    [5.9, 3.0, 5.1, 1.8]
Name: x, Length: 149, dtype: object

In [51]:
#Functii lambda
df['y'] =df['class'].apply(lambda x: x+1)
df['y']

0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: y, Length: 149, dtype: int64

In [52]:
df.to_csv("iris_ok.csv", index = False)

In [64]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors= len(np.unique(df['y'])))


In [65]:
neigh.fit(df[df.columns[:4]].values.tolist(), df['y'])

KNeighborsClassifier(n_neighbors=3)

In [66]:
neigh.predict([[5.2,3.6,1.39,0.2]])

array([1])

In [67]:
from pyod.models.knn import KNN
from sklearn.model_selection import train_test_split

In [68]:
clf = KNN()
clf.fit(df[df.columns[:4]].values.tolist(), df['y'])

/usr/local/lib/python3.10/dist-packages/pyod/models/base.py:430: UserWarning: y should not be presented in unsupervised learning.
  warnings.warn(


KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [69]:
y_train_pred = clf.labels_
clf.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
y_trains_scores = clf.decision_scores_
clf.decision_scores_

array([0.14142136, 0.2236068 , 0.26457513, 0.26457513, 0.2236068 ,
       0.38729833, 0.31622777, 0.2236068 , 0.36055513, 0.2       ,
       0.33166248, 0.3       , 0.24494897, 0.5       , 0.58309519,
       0.64031242, 0.4       , 0.17320508, 0.51961524, 0.31622777,
       0.36055513, 0.28284271, 0.53851648, 0.38729833, 0.4472136 ,
       0.3       , 0.26457513, 0.2236068 , 0.2236068 , 0.24494897,
       0.2236068 , 0.34641016, 0.45825757, 0.47958315, 0.2       ,
       0.33166248, 0.36055513, 0.3       , 0.3       , 0.17320508,
       0.24494897, 0.79372539, 0.31622777, 0.42426407, 0.47958315,
       0.26457513, 0.33166248, 0.2236068 , 0.28284271, 0.2236068 ,
       0.51961524, 0.38729833, 0.50990195, 0.43588989, 0.38729833,
       0.37416574, 0.45825757, 0.78740079, 0.31622777, 0.53851648,
       0.72111026, 0.37416574, 0.58309519, 0.43588989, 0.53851648,
       0.38729833, 0.42426407, 0.37416574, 0.70710678, 0.3       ,
       0.46904158, 0.41231056, 0.43588989, 0.45825757, 0.38729